#!/bin/sh

set -e

FILE_ENV=$1

if [ -z "$FILE_ENV" ]; then
    echo 'A .env file is required as argument'
    exit 1
fi

if [ -f $FILE_ENV ]; then
    export $(cat $FILE_ENV | xargs)

    __mysqldump.sh
else
    echo "file \`$FILE_ENV\` was not found"
    exit 1
fi
