#!/bin/sh

set -e

FILE_ENV=$1

if [[ -z "$FILE_ENV" ]]; then
    __mysqldump.sh
    exit 0
fi

if [[ -f $FILE_ENV ]]; then
    enve -f $FILE_ENV __mysqldump.sh
else
    echo "file \`$FILE_ENV\` was not found"
    exit 1
fi
