name: devel
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  docker:
    name: Docker test
    strategy:
      matrix:
        arch:
          - linux/amd64
          - linux/386
          - linux/arm64
          - linux/arm/v7
          - linux/arm/v6
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: alpine-mysql-client-${{ matrix.arch }}-buildx-${{ github.sha }}
          restore-keys: |
            alpine-mysql-client-${{ matrix.arch }}-buildx-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and Test
        uses: docker/build-push-action@v4
        with:
          push: false
          context: .
          platforms: ${{ matrix.arch }}
          file: Dockerfile
          tags: joseluisq/alpine-mysql-client:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
